/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv --include-runtime false cloudflare-env.d.ts` (hash: 9791acb4495a7ffe4faf25cc5294bcfd)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env {
		RATE_LIMIT: KVNamespace;
		ASSETS: Fetcher;
		ASK_RL_PER_MINUTE: "5";
		ASK_RL_PER_DAY: "30";
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ASK_RL_PER_MINUTE" | "ASK_RL_PER_DAY">> {}
}
